|DROP TABLE IF EXISTS USERS;
|CREATE TABLE IF NOT EXISTS USERS (
|  ID IDENTITY NOT NULL PRIMARY KEY,
|  NAME VARCHAR(64) NOT NULL,
|  CITY VARCHAR(64) NOT NULL,
|  AGE INT NOT NULL,
|  SINGLE BOOLEAN NOT NULL
|);

|DROP TABLE IF EXISTS SUBJECTS;
|CREATE TABLE IF NOT EXISTS SUBJECTS (
|  ID IDENTITY NOT NULL PRIMARY KEY,
|  YEAR INT NOT NULL,
|  SUBJECT_NAME VARCHAR(64) NOT NULL,
|  APPROVED_SUBJECT BOOLEAN NOT NULL
|);

DROP TABLE IF EXISTS MARKS;
CREATE TABLE IF NOT EXISTS MARKS(
  ID IDENTITY NOT NULL PRIMARY KEY,
  MARK INT NOT NULL,
  FECHA DATE NOT NULL
);

DROP TABLE IF EXISTS TEACHERS;
CREATE TABLE IF NOT EXISTS TEACHERS(
  ID IDENTITY NOT NULL PRIMARY KEY,
  TEACHER_NAME VARCHAR (64) NOT NULL,
  SUBJECT VARCHAR (64) NOT NULL
);

DROP TABLE IF EXISTS UNIVERSITIES;
CREATE TABLE IF NOT EXISTS UNIVERSITIES (
  ID IDENTITY AUTO_INCREMENT,
  UNIVERSITY_NAME VARCHAR (64) NOT NULL,
  CITY VARCHAR (64) NOT NULL,
  UNIVERSITY_YEAR INT NOT NULL,
  ONLINE BOOLEAN NOT NULL
);


INSERT INTO USERS(ID, NAME, CITY, AGE, SINGLE);
VALUES (1,"HENRY" , "Madrid", 30, true);

INSERT INTO SUBJECTS(ID, YEAR, SUBJECT_NAME, APPROVED_SUBJECT);
VALUES (2,2020,"Xname",true );