DROP TABLE IF EXISTS USERS;
CREATE TABLE IF NOT EXISTS USERS (
  ID IDENTITY NOT NULL,
  NAME VARCHAR(64) NOT NULL,
  CITY VARCHAR(64) NOT NULL,
  AGE INT NOT NULL,
  SINGLE BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS SUBJECTS;
CREATE TABLE IF NOT EXISTS SUBJECTS (
  ID IDENTITY NOT NULL,
  YEAR INT NOT NULL,
  SUBJECT_NAME VARCHAR(64) NOT NULL,
  APPROVED_SUBJECT BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS MARKS;
CREATE TABLE IF NOT EXISTS MARKS(
  ID IDENTITY NOT NULL,
  MARK INT NOT NULL,
  FECHA DATE NOT NULL
);

DROP TABLE IF EXISTS TEACHERS;
CREATE TABLE IF NOT EXISTS TEACHERS(
  ID IDENTITY NOT NULL,
  TEACHER_NAME VARCHAR (64) NOT NULL,
  SUBJECT VARCHAR (64) NOT NULL,
  CITY VARCHAR (64) NOT NULL
);

DROP TABLE IF EXISTS UNIVERSITIES;
CREATE TABLE IF NOT EXISTS UNIVERSITIES (
  ID IDENTITY AUTO_INCREMENT,
  UNIVERSITY_NAME VARCHAR (64) NOT NULL,
  CITY VARCHAR (64) NOT NULL,
  UNIVERSITY_YEAR INT NOT NULL,
  ONLINE BOOLEAN NOT NULL
);

// USERS

INSERT INTO USERS(ID, NAME, CITY, AGE, SINGLE)
  VALUES (1,'Henry', 'Madrid', 30, true);
INSERT INTO USERS(ID, NAME, CITY, AGE, SINGLE)
  VALUES (2,'Pepe', 'Valencia',33,true);
INSERT INTO USERS(ID, NAME, CITY, AGE, SINGLE)
  VALUES(3,'Maria','Salamanca',23,true);
INSERT INTO USERS(ID, NAME, CITY, AGE, SINGLE)
  VALUES (4,'Francisco', 'Burgos', 22, true);
INSERT INTO USERS(ID, NAME, CITY, AGE, SINGLE)
  VALUES (5,'Laura','Malaga',28,false);
INSERT INTO USERS(ID, NAME, CITY, AGE, SINGLE)
  VALUES(6,'Luis','Granada',31,false);



//  UNIVERSITIES

INSERT INTO UNIVERSITIES(ID,UNIVERSITY_NAME,CITY,UNIVERSITY_YEAR,ONLINE)
  VALUES ( 1,'Universidad Autonoma de Madrid', 'Madrid', 2019, true );
INSERT INTO UNIVERSITIES(ID,UNIVERSITY_NAME,CITY,UNIVERSITY_YEAR,ONLINE)
  VALUES ( 2,'Universidad de Burgos', 'Burgos', 2018, false );
INSERT INTO UNIVERSITIES(ID,UNIVERSITY_NAME,CITY,UNIVERSITY_YEAR,ONLINE)
  VALUES ( 3,'Universidad Almeria', 'Almeria', 2020, true );
INSERT INTO UNIVERSITIES(ID,UNIVERSITY_NAME,CITY,UNIVERSITY_YEAR,ONLINE)
  VALUES ( 4,'Universidad de Granada', 'Granada', 2020, true );
INSERT INTO UNIVERSITIES(ID,UNIVERSITY_NAME,CITY,UNIVERSITY_YEAR,ONLINE)
  VALUES ( 5,'Universidad Salamanca', 'Salamanca', 2019, false );
INSERT INTO UNIVERSITIES(ID,UNIVERSITY_NAME,CITY,UNIVERSITY_YEAR,ONLINE)
  VALUES ( 6,'Universidad de Sevilla', 'Sevilla', 2019, true );

//  SUBJECTS

INSERT INTO SUBJECTS(ID, YEAR, SUBJECT_NAME, APPROVED_SUBJECT)
  VALUES (1,2018,'Java Programming',false );
INSERT INTO SUBJECTS(ID, YEAR, SUBJECT_NAME, APPROVED_SUBJECT)
  VALUES (2,2017,'All About Sql',true );
INSERT INTO SUBJECTS(ID, YEAR, SUBJECT_NAME, APPROVED_SUBJECT)
  VALUES (3,2020,'http Server',false );
INSERT INTO SUBJECTS(ID, YEAR, SUBJECT_NAME, APPROVED_SUBJECT)
  VALUES (4,2020,'Scala for Beginners',true );
INSERT INTO SUBJECTS(ID, YEAR, SUBJECT_NAME, APPROVED_SUBJECT)
  VALUES (5,2019,'IntelliJ Idea',true );
INSERT INTO SUBJECTS(ID, YEAR, SUBJECT_NAME, APPROVED_SUBJECT)
  VALUES (6,2019,'bbdd',true );

//  TEACHERS

INSERT INTO TEACHERS(ID,TEACHER_NAME,SUBJECT,CITY)
  VALUES ( 1, 'Juan Jose Murillo', 'Java Programming','Madrid' );
INSERT INTO TEACHERS(ID,TEACHER_NAME,SUBJECT,CITY)
  VALUES ( 2, 'Rodrigo Calavera', 'All About Sql', 'Malaga' );
INSERT INTO TEACHERS(ID,TEACHER_NAME,SUBJECT,CITY)
  VALUES ( 3, 'Juan Jose Zorrilla', 'http Server', 'Granada' );
INSERT INTO TEACHERS(ID,TEACHER_NAME,SUBJECT,CITY)
  VALUES ( 4, 'Carlos Jean', 'Scala for Beginners', 'Salamanca' );
INSERT INTO TEACHERS(ID,TEACHER_NAME,SUBJECT,CITY)
  VALUES ( 5, 'Luis Rosales', 'IntelliJ idea', 'Almeria' );
INSERT INTO TEACHERS(ID,TEACHER_NAME,SUBJECT,CITY)
  VALUES ( 6, 'Antonio Valencia', 'bbdd', 'Asturias' );
