DROP TABLE IF EXISTS USERS;
CREATE TABLE IF NOT EXISTS USERS (
  ID IDENTITY NOT NULL PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  CITY VARCHAR(64) NOT NULL,
  AGE INT NOT NULL,
  SINGLE BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS SUBJECTS;
CREATE TABLE IF NOT EXISTS SUBJECTS (
  ID IDENTITY NOT NULL PRIMARY KEY,
  YEAR INT NOT NULL,
  SUBJECT_NAME VARCHAR(64) NOT NULL,
  APPROVED_SUBJECT BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS MARKS;
CREATE TABLE IF NOT EXISTS MARKS(
  ID IDENTITY NOT NULL PRIMARY KEY,
  MARK INT NOT NULL,
  FECHA DATE NOT NULL
);

DROP TABLE IF EXISTS TEACHERS;
CREATE TABLE IF NOT EXISTS TEACHERS(
  ID IDENTITY NOT NULL PRIMARY KEY,
  TEACHER_NAME VARCHAR (64) NOT NULL,
  SUBJECT VARCHAR (64) NOT NULL
);

DROP TABLE IF EXISTS UNIVERSITIES;
CREATE TABLE IF NOT EXISTS UNIVERSITIES (
  ID IDENTITY AUTO_INCREMENT,
  UNIVERSITY_NAME VARCHAR (64) NOT NULL,
  CITY VARCHAR (64) NOT NULL,
  UNIVERSITY_YEAR INT NOT NULL,
  ONLINE BOOLEAN NOT NULL
);


INSERT INTO USERS(ID, NAME, CITY, AGE, SINGLE)
  VALUES (1,'HENRY', 'MADRID', 30, true);
INSERT INTO USERS(ID, NAME, CITY, AGE, SINGLE)
  VALUES (2,'PEPE','VALENCIA',33,true);
INSERT INTO USERS(ID, NAME, CITY, AGE, SINGLE)
  VALUES(3,'MARIA','SALAMANCA',23,true);
INSERT INTO USERS(ID, NAME, CITY, AGE, SINGLE)
  VALUES (4,'FRANCISCO', 'BURGOS', 22, true);
INSERT INTO USERS(ID, NAME, CITY, AGE, SINGLE)
  VALUES (5,'LAURA','MALAGA',28,false);
INSERT INTO USERS(ID, NAME, CITY, AGE, SINGLE)
  VALUES(6,'LUIS','GRANADA',31,false);

INSERT INTO SUBJECTS(ID, YEAR, SUBJECT_NAME, APPROVED_SUBJECT)
  VALUES (2,2020,'Xname',true );